name: Performance Test

on:
  workflow_dispatch:   # run manually

jobs:
  performance:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Taurus
        run: |
          sudo apt update
          sudo apt install -y python3-pip
          pip3 install bzt

      - name: Run Performance Test on BlazeMeter
        env:
          BLAZEMETER_API_KEY: ${{ secrets.BLAZEMETER_API_KEY }}
          BLAZEMETER_API_SECRET: ${{ secrets.BLAZEMETER_API_SECRET }}
        run: |
          bzt performance.yaml
